### ISSUE TITLE
Alignment with windIO

### ISSUE THREAD

**Issue by SimonHH** [IEC-61400-15/eya_def#70]
Was there a discussion to align the wind EYA DEF JSON Schema with the windIO (https://windio.readthedocs.io/en/latest/) developed as part of IEA Wind Task 37?

Although the scope may be a bit different I still see potential to at least align wording and interoperability.

**Comment by jonssonchristian** [comment]
Hi @SimonHH, thanks for the suggestion and excuse the delayed response. I agree it makes sense to align with windIO to the degree practical, and in any case to ensure good interoperability. As far as I can see, this issue has the same scope as #67, so I will close this one and combine the conversation there.

**Comment by jonssonchristian** [comment]
Duplicate of #67
